version: "3"
services:
  app:
    image: node:lts-alpine
    command: sh -c "npm i && npm run bot"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      SUPPORT_CHAT_ID: ${SUPPORT_CHAT_ID}
      LOGGING_LEVEL: ${LOGGING_LEVEL}

      DB_HOST: ${MYSQL_DB_HOST}
      DB_NAME: ${MYSQL_DB_NAME}
      DB_USERNAME: ${MYSQL_DB_USERNAME}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: supportbot
    ports:
      - "3306:3306"

volumes:
  mysql:
